spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #로거를 통해 출력
    org.hibernate.type: trace

currency:
  api:
    url: http://apilayer.net/api/live
    access-key: ee50cd7cc73c9b7a7bb3d9617cfb6b9c
    currencies: KRW,JPY,PHP
